package pl.edu.agh.mobilecodereviewer.view.activities;

import android.os.Bundle;
import android.view.Menu;
import android.view.MenuItem;
import android.widget.ArrayAdapter;
import android.widget.ListView;

import com.google.common.base.Functions;
import com.google.common.collect.Lists;
import com.google.inject.Inject;

import java.util.List;

import pl.edu.agh.mobilecodereviewer.R;
import pl.edu.agh.mobilecodereviewer.controllers.api.ChangesExplorerController;
import pl.edu.agh.mobilecodereviewer.model.ChangeInfo;
import pl.edu.agh.mobilecodereviewer.view.api.ChangesExplorerView;
import roboguice.activity.RoboActivity;
import roboguice.inject.InjectView;

/**
 * Activity show list of Changes and enables navigating through them
 * @author AGH
 * @version 0.1
 * @since 0.1
 */
public class ChangesExplorer extends RoboActivity implements ChangesExplorerView {

    /**
     * Associated controller which make actions to activity events
     */
    @Inject
    private ChangesExplorerController controller;

    /**
     * List of changes view
     */
    @InjectView(R.id.listView)
    private ListView listView;

    /**
     * No arg constructor,main for use by di and android framework
     */
    public ChangesExplorer() {
    }

    /**
     * Construct activity with given controller,for test only
     * @param controller Controller to be used
     */
    public ChangesExplorer(ChangesExplorerController controller) {
        this.controller = controller;
    }

    /**
     * Invoked on start of the acivity, initialize view,
     * and show list of changes
     * @param savedInstanceState Last state of the activity
     */
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_changes_explorer);

        controller.updateChanges(this);
    }


    /**
     * Autogenerated?
     * @param menu
     * @return
     */
    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.changes_explorer, menu);
        return true;
    }

    /**
     * Autogenerated?
     * @param item
     * @return
     */
    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        int id = item.getItemId();
        if (id == R.id.action_settings) {
            return true;
        }
        return super.onOptionsItemSelected(item);
    }

    /**
     * According to given list of changes , displays it
     * on the list of changes on frame
     * @param changes List of changes to display
     */
    @Override
    public void showChanges(List<ChangeInfo> changes) {
        List<String> strChanges = Lists.transform( changes, Functions.toStringFunction());

        ArrayAdapter<String> adapter = new ArrayAdapter<>( this,
                android.R.layout.simple_list_item_1,
                android.R.id.text1,
                strChanges );

        
        listView.setAdapter(adapter);
    }
}


























